### ISSUE TITLE
Investigate the cause of the error in the RedGPU sample

### ISSUE THREAD

**Issue by cx20** [cx20/webgpu-test#60]
Updating the `RedGPU` doesn't draw anything, so I need to investigate the cause of the error.

**Comment by redcamel** [comment]
![image](https://user-images.githubusercontent.com/820587/132285837-d13b1ecb-c3df-4b2c-b5e1-06255518978b.png)
現在変更されたAPIを無理にフレームワーク内に無理に合わせた部分があります。
attachment関連部分であり、
フラグメントシェーダの作成時
layout（location=1）out vec4 out_MouseColorID_Depth;を入力してくれれば動作します。

**Comment by cx20** [comment]
@redcamel ありがとうございます！手厚いサポートのおかげで再びRedGPUのサンプルが動き出しました！

https://cx20.github.io/webgpu-test/examples/redgpu/triangle/index.html

![image](https://user-images.githubusercontent.com/1833979/132351037-da3ccbcf-1809-4bc6-9602-c923412d3db0.png)

**Comment by cx20** [comment]
@redcamel The sample below now gives the error again. Do you have any advice for a solution?
https://cx20.github.io/webgpu-test/examples/redgpu/triangle/index.html

> ShareGLSL:1
> Failed to load resource: the server responded with a status of 404 ()

https://redcamel.github.io/RedGPU/src/base/ShareGLSL

**Comment by redcamel** [comment]
@cx20 
![image](https://user-images.githubusercontent.com/820587/155261281-c22370a1-224b-4d39-96be-b767be97c0f4.png)
.jsが抜けました。

**Comment by cx20** [comment]
@redcamel
이 코드의 문제입니까?

https://github.com/redcamel/RedGPU/blob/ca786361ae3f4a957f966eff3142a251e879066f/src/base/BasePostEffect.js#L17
```JavaScript
import ShareGLSL from "./ShareGLSL";
```

**Comment by redcamel** [comment]
@cx20 Oh my god.....
i'm fixed import path fix.... ㅠ_ㅠ

**Comment by cx20** [comment]
Thank you for the correction. I confirmed that the sample started moving again.
